/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mini_;

import java.awt.Color;
import java.awt.*;
import java.awt.event.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Danny
 */
public class juego extends javax.swing.JFrame {
    static String palabra;
    static int vidas;
    static char aux[];
    static String fin;
    /**
     * Creates new form juego
     */
    public juego() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        palabra = saes.msj;
        vidas = 7;
        vida.setText("Tienes:  " + vidas  + " vidas");
        aux = new char[palabra.length()];
        for(int i=0; i<palabra.length(); i++){
            if(palabra.charAt(i)== ' '){
                aux[i]=' ';
            }else{
                aux[i]='-';
            }
        }
        fin = String.valueOf(aux);
        pala.setText(fin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vida = new javax.swing.JLabel();
        pala = new javax.swing.JLabel();
        juega = new javax.swing.JButton();
        val = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vida.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        vida.setForeground(new java.awt.Color(204, 0, 0));

        pala.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N

        juega.setBackground(new java.awt.Color(0, 0, 0));
        juega.setForeground(new java.awt.Color(255, 255, 255));
        juega.setText("Juega");
        juega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juegaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("Ahorcado");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Ingresa una letra y juega:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(vida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(val, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(juega, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(juega, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(val, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(63, 63, 63)
                .addComponent(pala, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(vida, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void juegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juegaActionPerformed
        // TODO add your handling code here:
        String pa;
        int cont=0;
        if(vidas==0){
            JOptionPane.showMessageDialog(null,"PERDISTE");
            JOptionPane.showMessageDialog(null,"Palabra(s): " + palabra);
            saes s = new saes();
            s.setVisible(true);
            this.dispose(); 
        }else{
            if(val.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"CAMPO VACIO");
                juega.setBackground(Color.red);
            }else{
            juega.setBackground(Color.black);
            fin = String.valueOf(aux);
            if(fin.equals(palabra)){
                JOptionPane.showMessageDialog(null,"HAS GANADO!");
                JOptionPane.showMessageDialog(null,"Palabra(s): " + palabra);
                saes s = new saes();
                s.setVisible(true);
                this.dispose();
            }else{
               pa = val.getText();
                for(int i=0; i<palabra.length(); i++){
                    if(palabra.charAt(i)== ' '){
                 }else{
                        if(palabra.charAt(i) == pa.charAt(0)){
                            aux[i] = pa.charAt(0);
                            cont++;
                        }
                    }
              }
                fin = String.valueOf(aux);
                pala.setText(fin);
                if(cont==0)vidas--;
            }
                vida.setText("Tienes:  " + vidas  + " vidas");
           }
        }
        
    }//GEN-LAST:event_juegaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new juego().setVisible(true);
            }
            
        });
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton juega;
    private javax.swing.JLabel pala;
    private javax.swing.JTextField val;
    private javax.swing.JLabel vida;
    // End of variables declaration//GEN-END:variables
}
